### ISSUE TITLE
Spatial Access Priority FormElement

### ISSUE THREAD

**Issue by underbluewaters** [seasketch/next#191]
Collects spatial information from the survey respondent, for one or more sectors. First test of collecting spatial information as a part of surveys, and the primary use case for BPC sites.

### Tasks

- [x] Collect various use cases, including SAP but also simpler spatial input surveys from the past and look for common elements
- [ ] Sketch (pen & paper) workflows for spatial entry on both desktop and mobile devices
- [ ] Update database schema to repurpose sketch classes for use in surveys
  - [ ] relations between sketch_classes, form_elements, surveys, responses, and sketches
  - [ ] Add new access control rules
  - [ ] Support access to spatial features for a limited amount of time when filling out a survey anonymously
  - [ ] Access to data for downloading/summarizing responses
  - [x] special functions for creating new spatial input form elements, or database triggers?
- [ ] Create admin interfaces to manage spatial input
  - [x] support for conditional fields within sketch class forms?
- [ ] Create client user interfaces for walking through spatial input
- [x] Think through issues with highly-complex inputs and preprocessing, and offline use
- [x] Support for custom basemap(s)
