### ISSUE TITLE
Survey Admin Interface

### ISSUE THREAD

**Issue by underbluewaters** [seasketch/next#195]
Project admins need a means to create and edit surveys.

### Tasks

- [x] Determine layout of editing interface
- [x] Add way to create surveys
  - [x]  Linked to #196 
- [x] Add function to delete surveys
- [x] Add means to create new formelements
- [x] FormElements should have a way to specify a default set of config options
- [x] Make body FormElement body editable in-place when in editing mode
- [x] Add editable representation/form for each existing FormElement type
- [x] Means to set question sort order
