### ISSUE TITLE
ThankYou Form Element

### ISSUE THREAD

**Issue by underbluewaters** [seasketch/next#219]
Complement to the WelcomeMessage, this should be a required rich-text page that ends a survey.

**Comment by underbluewaters** [comment]
## Task list

- [ ] Get listed in proper place in SurveyFormEditor
- [ ] Sort into proper place in SurveyApp
- [ ] Make sure newly added elements don't appear after ThankYou
- [ ] Shouldn't be deletable
- [ ] Don't show [Next] button on that page
- [ ] Add configuration to support multiple responses
- [ ] Social media sharing buttons
- [ ] Storybook test cases
- [ ] Unit tests

**Comment by underbluewaters** [comment]
Closed in #55109a5
