### ISSUE TITLE
Finish homepage smoke tests

### ISSUE THREAD

**Issue by underbluewaters** [seasketch/next#244]
Homepage smoke tests are the first integration tests to run, ensuring the client boots and homepage renders. They also verify some important navigation elements are present and functioning.

### Tasks

- [x] Complete any pending or failing tests in homepage.spec.js
- [x] Improve the test for project creation options, verifying the user can navigate from the homepage to the page that includes a form to create a new project
- [x] Test that there is a link to the project listings page, and that the user can follow it
- [x] Fix missing sign in link on mobile (see below)
- [x] Make sure nav link tests are exercised and are working on mobile. This may require restructuring the test so that the whole block is run on mobile, rather than just a few pieces. See [cypress' viewport docs](https://docs.cypress.io/api/commands/viewport) for examples.
- [x] Ensure all key buttons and links are referenced by id attribute rather than text, adding them to the react components if necessary.

Also, just generally use your judgement to identify any issues on the homepage or important test assertions to add.

### Links on mobile

On small mobile devices, instead of a plain sign-in link there should be a "hamburger menu" which opens an overlay with navigation links and the sign-in button. This menu is no longer showing up. I took a quick look and the necessary code is in [Header.tsx](https://github.com/seasketch/next/blob/master/packages/client/src/header/Header.tsx#L105) but has been commented out. Please restore it and verify it works correctly and navigation links show up. Also, remove the `projectMode` setting on Header. That mode assumed this same component might work in different contexts of the app, but now it is only used on the homepage so no need for it to adapt to different "modes". I think this will restore rendering of nav links in the overlay as well.

### First issue best practices

I'm trying to follow [GitHub Flow](https://docs.github.com/en/get-started/quickstart/github-flow) as much as possible. For this issue that will mean creating a dedicated branch and pull request. Name the branch something descriptive like test-homepage or feature-homepage-tests. @underbluewaters can review before merging into `master`. When complete, all the tests run through GitHub actions should be passing again.

**Comment by underbluewaters** [comment]
Was closed in #242
