### ISSUE TITLE
Add "survey facilitator" type role who can access and update responses

### ISSUE THREAD

**Issue by underbluewaters** [seasketch/next#345]
This is a heavy lift that I've resisted but it may be a tech fix for what could be a serious bottleneck in our work. If our team has to be responsible for doing all edits it could get unmanageable.

### Tasks

  - [ ] Scope out what special permissions this role will have. They will need to be able to edit both survey responses and sketches.
  - [ ] Determine how to represent and assign these permissions and update the database schema and RLS
  - [ ] Update UI to enable managing permissions
  - [ ] Update "route blockers" to account for this detail
  - [ ] Make sure affordances are there for facilitators to find their way to the dashboard

### Open Questions

  * Given the risk with this new functionality, should we "version" edits? Would be hard/impossible to do with spatial data but pretty easy with other data.
  * Can facilitators edit anyone's responses, or just their own. It might be hard to limit it to just those they created since people can't even reliably fill out the facilitator field.
