### ISSUE TITLE
Offline surveys de-risking task list

### ISSUE THREAD

**Issue by underbluewaters** [seasketch/next#369]
- [x] Put together estimates of how many tiles and how many bytes would be required per-basemap
- [x] Make a quick PWA that runs mapbox-gl-js offline and see how that goes
- [x] Contact Marena and get clarity on limitations mapbox-gl-js and mapbox services when used offline. Particularly around telemetry and possible terms of service violations around tile redistribution.
- [ ] Make sure you will be able to come up with a solution to cache graphql queries
- [x] Investigate how code-splitting will impact caching of the app, and whether it's possible to just cache the assets needed for surveys rather than the entire app
- [x] Test populating cache with map tiles. How large is the dataset? How does the browser respond to having such a large cache? What's performance like?
- [ ] Decide how to download tiles. Should all clients download direct from mapbox, or should you try sideloading to reduce costs?
